cat("How many nucleotides long? ")
n <- as.numeric(readLines(file("stdin"), 1))
cat("What is frequency of A? ")
pA <- as.numeric(readLines(file("stdin"), 1))
cat("What is frequency of C? ")
pC <- as.numeric(readLines(file("stdin"), 1))
cat("What is frequency of G? ")
pG <- as.numeric(readLines(file("stdin"), 1))
cat("What is frequency of T? ")
pT <- as.numeric(readLines(file("stdin"), 1))
print("n is: ")
print(n)
print("pA is: ")
print(pA)
print("pC is: ")
print(pC)
print("pG is: ")
print(pG)
print("pT is: ")
print(pT)